/*
 * ARCTable.java
 *
 * Created on 24. April 2008, 10:31
 */
package at.ac.arcs.rgg.element.maimporter.ui.arrayheaderselection;

import javax.swing.JScrollPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author  ahmet
 */
public class ARCTable extends javax.swing.JPanel {

    private RowHeaderTable rowHeader;
    private MyJTable table;

    /** Creates new form ARCTable */
    public ARCTable() {
        initComponents();
        table = new MyJTable();
        tableScrollPane.setViewportView(table);         
    }

    public void setModel(MyDefaultTableModel model){
        table.setModel(model);
        initRowHeader();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();

        setMinimumSize(new java.awt.Dimension(25, 500));
        setLayout(new java.awt.GridLayout(1, 1));
        add(tableScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    public void resizeColumn(){
        table.resizeColumn();
    }
    
    protected void initRowHeader(){
        rowHeader = new RowHeaderTable(table);
        tableScrollPane.setRowHeaderView(rowHeader);
        JTableHeader corner = rowHeader.getTableHeader();
        tableScrollPane.setCorner(JScrollPane.UPPER_LEFT_CORNER, corner);
        new JScrollPaneAdjuster(tableScrollPane);
        new JTableRowHeaderResizer(tableScrollPane).setEnabled(false);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
